name: Check

on:
  pull_request:

  push:
    branches:
      - 2.8.x # Check 2.8.x branch after merge

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    uses: playframework/.github/.github/workflows/cmd.yml@v2
    with:
      java: 11, 8
      cmd: sbt test g8Test

  finish:
    name: Finish
    needs: # Should be last
      - "tests"
    uses: playframework/.github/.github/workflows/rtm.yml@v2
